/* FabMesh i18n - curated multi-language labels for the new tools/modals
 * (generated by the i18n-curate-labels workflow, 2026-06-22, 5 language agents).
 * Load AFTER lang/_additions4.js. The 5 texture-tool labels keep their FR from
 * _additions4.js (clearer names), so they are intentionally NOT re-registered for 'fr'. */
(function () {
  if (!window.FabI18n || !window.FabI18n.register) return;

  window.FabI18n.register('fr', {
    'Multi-Views': 'Multi-vues',
    'Extend': 'Étendre',
    'Brightness': 'Luminosité',
    'Color Pick': 'Pipette',
    'Blur Brush': 'Brosse de flou',
    'Symmetrize': 'Symétriser',
    'Recolor': 'Recolorer',
    'What to recolor': 'Quoi recolorer',
    'Colour': 'Couleur',
    'Strength': 'Intensité',
    'Detection precision': 'Précision de détection',
    'Detection padding': 'Marge de détection',
    'Age': 'Âge',
    'Younger': 'Plus jeune',
    'Older': 'Plus âgé',
    'Neutral': 'Neutre',
    'Variation guide (optional)': 'Guide de variation (facultatif)',
    'Enhance texture': 'Améliorer la texture',
    'Variant': 'Variante',
    'Which part? (the AI detects it — no painting needed)': 'Quelle partie ? (l\'IA la détecte — pas besoin de peindre)',
    'Detect (AI)': 'Détecter (IA)',
    'What should this area look like?': 'À quoi doit ressembler cette zone ?',
    'Brush': 'Brosse',
    'Clear paint': 'Effacer la peinture',
  });

  window.FabI18n.register('es', {
    'Re-bake from photo (HD)': 'Rehornear desde foto (HD)',
    'Texture variants': 'Variantes de textura',
    'Sharpen texture (x2)': 'Enfocar textura (x2)',
    'Re-texture all (AI)': 'Retexturizar todo (IA)',
    'Re-texture a region (AI)': 'Retexturizar una región (IA)',
    'Multi-Views': 'Multivistas',
    'Extend': 'Extender',
    'Brightness': 'Brillo',
    'Color Pick': 'Seleccionar color',
    'Blur Brush': 'Pincel de desenfoque',
    'Symmetrize': 'Simetrizar',
    'Style…': 'Estilo…',
    'Recolor': 'Recolorear',
    'What to recolor': 'Qué recolorear',
    'Colour': 'Color',
    'Strength': 'Intensidad',
    'Detection precision': 'Precisión de detección',
    'Detection padding': 'Margen de detección',
    'Age': 'Edad',
    'Younger': 'Más joven',
    'Older': 'Más viejo',
    'Neutral': 'Neutral',
    'Variation guide (optional)': 'Guía de variación (opcional)',
    'Enhance texture': 'Mejorar textura',
    'Variant': 'Variante',
    'Which part? (the AI detects it — no painting needed)': '¿Qué parte? (la IA la detecta — sin pintar)',
    'Detect (AI)': 'Detectar (IA)',
    'What should this area look like?': '¿Cómo debería verse esta zona?',
    'Brush': 'Pincel',
    'Clear paint': 'Borrar pintura',
  });

  window.FabI18n.register('zh', {
    'Re-bake from photo (HD)': '从照片重新烘焙 (HD)',
    'Texture variants': '贴图变体',
    'Sharpen texture (x2)': '锐化贴图 (x2)',
    'Re-texture all (AI)': '全部重新贴图 (AI)',
    'Re-texture a region (AI)': '重新贴图区域 (AI)',
    'Multi-Views': '多视图',
    'Extend': '扩展',
    'Brightness': '亮度',
    'Color Pick': '拾色',
    'Blur Brush': '模糊笔刷',
    'Symmetrize': '对称化',
    'Style…': '风格…',
    'Recolor': '重新着色',
    'What to recolor': '要重新着色的内容',
    'Colour': '颜色',
    'Strength': '强度',
    'Detection precision': '检测精度',
    'Detection padding': '检测边距',
    'Age': '年龄',
    'Younger': '更年轻',
    'Older': '更年长',
    'Neutral': '中性',
    'Variation guide (optional)': '变化引导（可选）',
    'Enhance texture': '增强贴图',
    'Variant': '变体',
    'Which part? (the AI detects it — no painting needed)': '哪个部位？（AI 自动检测 — 无需涂抹）',
    'Detect (AI)': '检测 (AI)',
    'What should this area look like?': '此区域应呈现什么效果？',
    'Brush': '笔刷',
    'Clear paint': '清除涂抹',
  });

  window.FabI18n.register('hi', {
    'Re-bake from photo (HD)': 'फ़ोटो से दोबारा बेक करें (HD)',
    'Texture variants': 'टेक्सचर वैरिएंट',
    'Sharpen texture (x2)': 'टेक्सचर शार्प करें (x2)',
    'Re-texture all (AI)': 'सब री-टेक्सचर करें (AI)',
    'Re-texture a region (AI)': 'एक क्षेत्र री-टेक्सचर करें (AI)',
    'Multi-Views': 'मल्टी-व्यू',
    'Extend': 'विस्तार करें',
    'Brightness': 'चमक',
    'Color Pick': 'रंग चुनें',
    'Blur Brush': 'ब्लर ब्रश',
    'Symmetrize': 'सममित करें',
    'Style…': 'स्टाइल…',
    'Recolor': 'रंग बदलें',
    'What to recolor': 'क्या रंग बदलना है',
    'Colour': 'रंग',
    'Strength': 'तीव्रता',
    'Detection precision': 'पहचान परिशुद्धता',
    'Detection padding': 'पहचान पैडिंग',
    'Age': 'आयु',
    'Younger': 'कम उम्र',
    'Older': 'अधिक उम्र',
    'Neutral': 'तटस्थ',
    'Variation guide (optional)': 'वैरिएशन गाइड (वैकल्पिक)',
    'Enhance texture': 'टेक्सचर बेहतर करें',
    'Variant': 'वैरिएंट',
    'Which part? (the AI detects it — no painting needed)': 'कौन सा हिस्सा? (AI इसे पहचान लेता है — पेंट करने की ज़रूरत नहीं)',
    'Detect (AI)': 'पहचानें (AI)',
    'What should this area look like?': 'यह क्षेत्र कैसा दिखना चाहिए?',
    'Brush': 'ब्रश',
    'Clear paint': 'पेंट साफ़ करें',
  });

  window.FabI18n.register('ar', {
    'Re-bake from photo (HD)': 'إعادة الخَبز من صورة (HD)',
    'Texture variants': 'متغيّرات الخامة',
    'Sharpen texture (x2)': 'زيادة حدّة الخامة (x2)',
    'Re-texture all (AI)': 'إعادة كَسْو الكل (ذكاء اصطناعي)',
    'Re-texture a region (AI)': 'إعادة كَسْو منطقة (ذكاء اصطناعي)',
    'Multi-Views': 'مناظر متعدّدة',
    'Extend': 'توسيع',
    'Brightness': 'السطوع',
    'Color Pick': 'التقاط اللون',
    'Blur Brush': 'فرشاة التمويه',
    'Symmetrize': 'تماثل',
    'Style…': 'النمط…',
    'Recolor': 'إعادة التلوين',
    'What to recolor': 'ما الذي يُعاد تلوينه',
    'Colour': 'اللون',
    'Strength': 'الشدّة',
    'Detection precision': 'دقّة الكشف',
    'Detection padding': 'هامش الكشف',
    'Age': 'العمر',
    'Younger': 'أصغر سنًّا',
    'Older': 'أكبر سنًّا',
    'Neutral': 'محايد',
    'Variation guide (optional)': 'دليل التنويع (اختياري)',
    'Enhance texture': 'تحسين الخامة',
    'Variant': 'متغيّر',
    'Which part? (the AI detects it — no painting needed)': 'أي جزء؟ (يكتشفه الذكاء الاصطناعي — لا حاجة للرسم)',
    'Detect (AI)': 'كشف (ذكاء اصطناعي)',
    'What should this area look like?': 'كيف ينبغي أن تبدو هذه المنطقة؟',
    'Brush': 'الفرشاة',
    'Clear paint': 'مسح الطلاء',
  });
  // Fenetre des taches : onglets « En cours » / « Travaux finis » (2026-09-26).
  window.FabI18n.register('fr', {
    'Jobs': 'Tâches',
    'Finished': 'Travaux finis',
    'No running jobs': 'Aucune tâche en cours',
    'No finished jobs yet': 'Aucun travail fini pour l’instant',
  });
  window.FabI18n.register('es', {
    'Jobs': 'Tareas',
    'Finished': 'Terminadas',
    'No running jobs': 'Ninguna tarea en curso',
    'No finished jobs yet': 'Aún no hay tareas terminadas',
  });
  window.FabI18n.register('zh', {
    'Jobs': '任务',
    'Finished': '已完成',
    'No running jobs': '没有进行中的任务',
    'No finished jobs yet': '暂无已完成的任务',
  });
  window.FabI18n.register('hi', {
    'Jobs': 'कार्य',
    'Finished': 'पूर्ण',
    'No running jobs': 'कोई कार्य जारी नहीं',
    'No finished jobs yet': 'अभी तक कोई कार्य पूर्ण नहीं',
  });
  window.FabI18n.register('ar', {
    'Jobs': 'المهام',
    'Finished': 'المنتهية',
    'No running jobs': 'لا توجد مهام قيد التنفيذ',
    'No finished jobs yet': 'لا توجد مهام منتهية بعد',
  });
  // Animation : lecture sur place (2026-09-26).
  window.FabI18n.register('fr', { 'In place': 'Sur place' });
  window.FabI18n.register('es', { 'In place': 'En el sitio' });
  window.FabI18n.register('zh', { 'In place': '原地' });
  window.FabI18n.register('hi', { 'In place': 'एक ही जगह' });
  window.FabI18n.register('ar', { 'In place': 'في المكان' });
  // Rig : editeur des points du squelette (2026-09-26).
  window.FabI18n.register('fr', {
    'Skeleton points': 'Points du squelette',
    'Each point marks a place the skeleton must reach: foot tips, jaw, ears, tail. Drag a point onto the right spot, add one where the rig stops short, remove the ones you don\'t need, then re-generate the rig.':
      'Chaque point marque un endroit que le squelette doit atteindre : bouts des pieds, mâchoire, oreilles, queue. Glissez un point au bon endroit, ajoutez-en un là où le rig s\'arrête trop tôt, retirez ceux qui ne servent pas, puis régénérez le rig.',
    'Add point': 'Ajouter un point',
    'Re-generate rig with these points': 'Régénérer le rig avec ces points',
    'Reached by a bone': 'Atteint par un os',
    'Not reached yet': 'Pas encore atteint',
    'Then click the mesh where the new point goes': 'Cliquez ensuite sur le maillage, là où va le nouveau point',
    'Back to the points of this rig': 'Revenir aux points de ce rig',
    'Rig the mesh again: the skeleton will reach every point': 'Rigger à nouveau le maillage : le squelette atteindra chaque point',
    'Drag a point to where the skeleton must reach. Right-drag pans, wheel zooms.': 'Glissez un point là où le squelette doit arriver. Clic droit glissé : déplacer la vue ; molette : zoom.',
    'Click the mesh where the new point goes (Esc to cancel).': 'Cliquez sur le maillage là où va le nouveau point (Échap pour annuler).',
    'Move the points the skeleton must reach (foot tips, jaw, ears, tail), then re-generate the rig.': 'Déplacez les points que le squelette doit atteindre (bouts des pieds, mâchoire, oreilles, queue), puis régénérez le rig.',
    'Generate a rig first, then adjust its skeleton points here.': 'Générez d\'abord un rig, puis ajustez ici les points de son squelette.',
    'Loading the rig…': 'Chargement du rig…',
    'Could not read this rig.': 'Impossible de lire ce rig.',
    'No points yet. Click “Add point”, then click the mesh.': 'Aucun point pour l\'instant. Cliquez sur « Ajouter un point », puis sur le maillage.',
    'Point': 'Point',
    'reached': 'atteint',
    'not reached': 'non atteint',
    'Remove this point': 'Retirer ce point',
    'The mesh this rig was made from is no longer in the project, so the points cannot be applied.': 'Le maillage d\'origine de ce rig n\'est plus dans le projet : les points ne peuvent pas être appliqués.',
  });
  window.FabI18n.register('es', {
    'Skeleton points': 'Puntos del esqueleto',
    'Each point marks a place the skeleton must reach: foot tips, jaw, ears, tail. Drag a point onto the right spot, add one where the rig stops short, remove the ones you don\'t need, then re-generate the rig.':
      'Cada punto marca un lugar al que debe llegar el esqueleto: puntas de los pies, mandíbula, orejas, cola. Arrastra un punto al lugar correcto, añade uno donde el rig se queda corto, quita los que no necesites y vuelve a generar el rig.',
    'Add point': 'Añadir punto',
    'Re-generate rig with these points': 'Regenerar el rig con estos puntos',
    'Reached by a bone': 'Alcanzado por un hueso',
    'Not reached yet': 'Aún no alcanzado',
    'Then click the mesh where the new point goes': 'Después haz clic en la malla donde va el nuevo punto',
    'Back to the points of this rig': 'Volver a los puntos de este rig',
    'Rig the mesh again: the skeleton will reach every point': 'Volver a riggear la malla: el esqueleto llegará a cada punto',
    'Drag a point to where the skeleton must reach. Right-drag pans, wheel zooms.': 'Arrastra un punto hasta donde debe llegar el esqueleto. Arrastre con botón derecho: desplazar; rueda: zoom.',
    'Click the mesh where the new point goes (Esc to cancel).': 'Haz clic en la malla donde va el nuevo punto (Esc para cancelar).',
    'Move the points the skeleton must reach (foot tips, jaw, ears, tail), then re-generate the rig.': 'Mueve los puntos a los que debe llegar el esqueleto (puntas de los pies, mandíbula, orejas, cola) y vuelve a generar el rig.',
    'Generate a rig first, then adjust its skeleton points here.': 'Primero genera un rig y luego ajusta aquí los puntos de su esqueleto.',
    'Loading the rig…': 'Cargando el rig…',
    'Could not read this rig.': 'No se pudo leer este rig.',
    'No points yet. Click “Add point”, then click the mesh.': 'Aún no hay puntos. Haz clic en «Añadir punto» y luego en la malla.',
    'Point': 'Punto',
    'reached': 'alcanzado',
    'not reached': 'no alcanzado',
    'Remove this point': 'Quitar este punto',
    'The mesh this rig was made from is no longer in the project, so the points cannot be applied.': 'La malla de origen de este rig ya no está en el proyecto, así que no se pueden aplicar los puntos.',
  });
  window.FabI18n.register('zh', {
    'Skeleton points': '骨架点',
    'Each point marks a place the skeleton must reach: foot tips, jaw, ears, tail. Drag a point onto the right spot, add one where the rig stops short, remove the ones you don\'t need, then re-generate the rig.':
      '每个点标记骨架必须到达的位置：脚尖、下颌、耳朵、尾巴。把点拖到正确位置，在骨骼没有延伸到的地方添加点，删除不需要的点，然后重新生成骨骼绑定。',
    'Add point': '添加点',
    'Re-generate rig with these points': '用这些点重新生成绑定',
    'Reached by a bone': '已有骨骼到达',
    'Not reached yet': '尚未到达',
    'Then click the mesh where the new point goes': '然后在网格上点击新点的位置',
    'Back to the points of this rig': '恢复为此绑定的点',
    'Rig the mesh again: the skeleton will reach every point': '重新绑定网格：骨架将到达每个点',
    'Drag a point to where the skeleton must reach. Right-drag pans, wheel zooms.': '把点拖到骨架必须到达的位置。右键拖动平移，滚轮缩放。',
    'Click the mesh where the new point goes (Esc to cancel).': '在网格上点击新点的位置（按 Esc 取消）。',
    'Move the points the skeleton must reach (foot tips, jaw, ears, tail), then re-generate the rig.': '移动骨架必须到达的点（脚尖、下颌、耳朵、尾巴），然后重新生成绑定。',
    'Generate a rig first, then adjust its skeleton points here.': '请先生成绑定，然后在这里调整其骨架点。',
    'Loading the rig…': '正在加载绑定…',
    'Could not read this rig.': '无法读取此绑定。',
    'No points yet. Click “Add point”, then click the mesh.': '还没有点。点击“添加点”，然后点击网格。',
    'Point': '点',
    'reached': '已到达',
    'not reached': '未到达',
    'Remove this point': '删除此点',
    'The mesh this rig was made from is no longer in the project, so the points cannot be applied.': '此绑定所用的网格已不在项目中，无法应用这些点。',
  });
  window.FabI18n.register('hi', {
    'Skeleton points': 'कंकाल बिंदु',
    'Each point marks a place the skeleton must reach: foot tips, jaw, ears, tail. Drag a point onto the right spot, add one where the rig stops short, remove the ones you don\'t need, then re-generate the rig.':
      'हर बिंदु वह जगह दिखाता है जहाँ तक कंकाल को पहुँचना है: पैरों के सिरे, जबड़ा, कान, पूँछ। बिंदु को सही जगह खींचें, जहाँ रिग अधूरा रह जाए वहाँ नया बिंदु जोड़ें, अनावश्यक बिंदु हटाएँ, फिर रिग दोबारा बनाएँ।',
    'Add point': 'बिंदु जोड़ें',
    'Re-generate rig with these points': 'इन बिंदुओं से रिग दोबारा बनाएँ',
    'Reached by a bone': 'हड्डी पहुँच गई',
    'Not reached yet': 'अभी नहीं पहुँची',
    'Then click the mesh where the new point goes': 'फिर मेश पर वहाँ क्लिक करें जहाँ नया बिंदु जाना है',
    'Back to the points of this rig': 'इस रिग के बिंदुओं पर लौटें',
    'Rig the mesh again: the skeleton will reach every point': 'मेश को फिर से रिग करें: कंकाल हर बिंदु तक पहुँचेगा',
    'Drag a point to where the skeleton must reach. Right-drag pans, wheel zooms.': 'बिंदु को वहाँ खींचें जहाँ तक कंकाल को पहुँचना है। राइट-ड्रैग से दृश्य खिसकाएँ, व्हील से ज़ूम करें।',
    'Click the mesh where the new point goes (Esc to cancel).': 'मेश पर वहाँ क्लिक करें जहाँ नया बिंदु जाना है (रद्द करने के लिए Esc)।',
    'Move the points the skeleton must reach (foot tips, jaw, ears, tail), then re-generate the rig.': 'वे बिंदु खिसकाएँ जहाँ तक कंकाल को पहुँचना है (पैरों के सिरे, जबड़ा, कान, पूँछ), फिर रिग दोबारा बनाएँ।',
    'Generate a rig first, then adjust its skeleton points here.': 'पहले रिग बनाएँ, फिर यहाँ उसके कंकाल बिंदु समायोजित करें।',
    'Loading the rig…': 'रिग लोड हो रहा है…',
    'Could not read this rig.': 'यह रिग पढ़ा नहीं जा सका।',
    'No points yet. Click “Add point”, then click the mesh.': 'अभी कोई बिंदु नहीं। «बिंदु जोड़ें» पर क्लिक करें, फिर मेश पर।',
    'Point': 'बिंदु',
    'reached': 'पहुँचा',
    'not reached': 'नहीं पहुँचा',
    'Remove this point': 'यह बिंदु हटाएँ',
    'The mesh this rig was made from is no longer in the project, so the points cannot be applied.': 'जिस मेश से यह रिग बना था वह अब प्रोजेक्ट में नहीं है, इसलिए बिंदु लागू नहीं किए जा सकते।',
  });
  window.FabI18n.register('ar', {
    'Skeleton points': 'نقاط الهيكل',
    'Each point marks a place the skeleton must reach: foot tips, jaw, ears, tail. Drag a point onto the right spot, add one where the rig stops short, remove the ones you don\'t need, then re-generate the rig.':
      'كل نقطة تحدد مكانًا يجب أن يصل إليه الهيكل: أطراف القدمين، الفك، الأذنان، الذيل. اسحب النقطة إلى المكان الصحيح، وأضف نقطة حيث يتوقف الهيكل مبكرًا، واحذف ما لا تحتاجه، ثم أعد إنشاء الهيكل.',
    'Add point': 'إضافة نقطة',
    'Re-generate rig with these points': 'إعادة إنشاء الهيكل بهذه النقاط',
    'Reached by a bone': 'وصلت إليها عظمة',
    'Not reached yet': 'لم تصل إليها بعد',
    'Then click the mesh where the new point goes': 'ثم انقر على المجسم في مكان النقطة الجديدة',
    'Back to the points of this rig': 'العودة إلى نقاط هذا الهيكل',
    'Rig the mesh again: the skeleton will reach every point': 'إعادة تركيب الهيكل: سيصل الهيكل إلى كل نقطة',
    'Drag a point to where the skeleton must reach. Right-drag pans, wheel zooms.': 'اسحب النقطة إلى حيث يجب أن يصل الهيكل. السحب بالزر الأيمن للتحريك، والعجلة للتكبير.',
    'Click the mesh where the new point goes (Esc to cancel).': 'انقر على المجسم في مكان النقطة الجديدة (Esc للإلغاء).',
    'Move the points the skeleton must reach (foot tips, jaw, ears, tail), then re-generate the rig.': 'حرّك النقاط التي يجب أن يصل إليها الهيكل (أطراف القدمين، الفك، الأذنان، الذيل)، ثم أعد إنشاء الهيكل.',
    'Generate a rig first, then adjust its skeleton points here.': 'أنشئ هيكلًا أولًا، ثم اضبط نقاطه هنا.',
    'Loading the rig…': 'جارٍ تحميل الهيكل…',
    'Could not read this rig.': 'تعذرت قراءة هذا الهيكل.',
    'No points yet. Click “Add point”, then click the mesh.': 'لا توجد نقاط بعد. انقر «إضافة نقطة» ثم انقر على المجسم.',
    'Point': 'نقطة',
    'reached': 'تم الوصول',
    'not reached': 'لم يتم الوصول',
    'Remove this point': 'حذف هذه النقطة',
    'The mesh this rig was made from is no longer in the project, so the points cannot be applied.': 'المجسم الذي صُنع منه هذا الهيكل لم يعد في المشروع، لذا لا يمكن تطبيق النقاط.',
  });
  // Editeur de points : articulations deplacables + peau seule (2026-09-26).
  window.FabI18n.register('fr', {"Drag a point or a purple joint. Right-drag pans, wheel zooms.": "Glissez un point ou une articulation violette. Clic droit glissé : déplacer la vue ; molette : zoom.", "Joint (drag to move)": "Articulation (à glisser)", "No rig yet.": "Pas encore de rig.", "Re-skin only": "Peau seule", "Re-skin": "Recalculer", "Recompute the skin weights of this rig? The skeleton stays exactly as it is.": "Recalculer les poids de peau de ce rig ? Le squelette reste exactement tel quel.", "The mesh this rig was made from is no longer in the project, so the skin cannot be recomputed.": "Le maillage d'origine de ce rig n'est plus dans le projet : la peau ne peut pas être recalculée.", "Could not read the skeleton of this rig.": "Impossible de lire le squelette de ce rig.", "Skin only (skeleton kept)": "Peau seule (squelette conservé)", "Edited skeleton": "Squelette modifié"});
  window.FabI18n.register('es', {"Drag a point or a purple joint. Right-drag pans, wheel zooms.": "Arrastra un punto o una articulación morada. Arrastre con botón derecho: desplazar; rueda: zoom.", "Joint (drag to move)": "Articulación (arrastrar)", "No rig yet.": "Aún no hay rig.", "Re-skin only": "Solo la piel", "Re-skin": "Recalcular", "Recompute the skin weights of this rig? The skeleton stays exactly as it is.": "¿Recalcular los pesos de piel de este rig? El esqueleto se mantiene exactamente igual.", "The mesh this rig was made from is no longer in the project, so the skin cannot be recomputed.": "La malla de origen de este rig ya no está en el proyecto, así que no se puede recalcular la piel.", "Could not read the skeleton of this rig.": "No se pudo leer el esqueleto de este rig.", "Skin only (skeleton kept)": "Solo piel (esqueleto conservado)", "Edited skeleton": "Esqueleto editado"});
  window.FabI18n.register('zh', {"Drag a point or a purple joint. Right-drag pans, wheel zooms.": "拖动点或紫色关节。右键拖动平移，滚轮缩放。", "Joint (drag to move)": "关节（可拖动）", "No rig yet.": "还没有绑定。", "Re-skin only": "仅重算蒙皮", "Re-skin": "重算", "Recompute the skin weights of this rig? The skeleton stays exactly as it is.": "重新计算此绑定的蒙皮权重？骨架保持完全不变。", "The mesh this rig was made from is no longer in the project, so the skin cannot be recomputed.": "此绑定所用的网格已不在项目中，无法重新计算蒙皮。", "Could not read the skeleton of this rig.": "无法读取此绑定的骨架。", "Skin only (skeleton kept)": "仅蒙皮（保留骨架）", "Edited skeleton": "已编辑的骨架"});
  window.FabI18n.register('hi', {"Drag a point or a purple joint. Right-drag pans, wheel zooms.": "बिंदु या बैंगनी जोड़ खींचें। राइट-ड्रैग से दृश्य खिसकाएँ, व्हील से ज़ूम करें।", "Joint (drag to move)": "जोड़ (खींचकर हिलाएँ)", "No rig yet.": "अभी कोई रिग नहीं।", "Re-skin only": "केवल स्किन", "Re-skin": "फिर से गणना", "Recompute the skin weights of this rig? The skeleton stays exactly as it is.": "इस रिग के स्किन वेट फिर से गणना करें? कंकाल बिल्कुल वैसा ही रहेगा।", "The mesh this rig was made from is no longer in the project, so the skin cannot be recomputed.": "जिस मेश से यह रिग बना था वह अब प्रोजेक्ट में नहीं है, इसलिए स्किन फिर से नहीं गणना की जा सकती।", "Could not read the skeleton of this rig.": "इस रिग का कंकाल पढ़ा नहीं जा सका।", "Skin only (skeleton kept)": "केवल स्किन (कंकाल वही)", "Edited skeleton": "संपादित कंकाल"});
  window.FabI18n.register('ar', {"Drag a point or a purple joint. Right-drag pans, wheel zooms.": "اسحب نقطة أو مفصلًا بنفسجيًا. السحب بالزر الأيمن للتحريك، والعجلة للتكبير.", "Joint (drag to move)": "مفصل (اسحب للتحريك)", "No rig yet.": "لا يوجد هيكل بعد.", "Re-skin only": "الجلد فقط", "Re-skin": "إعادة الحساب", "Recompute the skin weights of this rig? The skeleton stays exactly as it is.": "إعادة حساب أوزان الجلد لهذا الهيكل؟ يبقى الهيكل كما هو تمامًا.", "The mesh this rig was made from is no longer in the project, so the skin cannot be recomputed.": "المجسم الذي صُنع منه هذا الهيكل لم يعد في المشروع، لذا لا يمكن إعادة حساب الجلد.", "Could not read the skeleton of this rig.": "تعذرت قراءة هيكل هذا الهيكل العظمي.", "Skin only (skeleton kept)": "الجلد فقط (مع إبقاء الهيكل)", "Edited skeleton": "هيكل معدّل"});
  // Editeur de points : « Save moved joints » (2026-09-28).
  window.FabI18n.register('fr', {"Save moved joints": "Enregistrer les articulations déplacées", "Saves a new version of the rig with the pink joints where you put them. The mesh does not change.": "Enregistre une nouvelle version du rig avec les articulations roses là où vous les avez mises. Le maillage ne change pas.", "Move a pink joint first.": "Déplacez d'abord une articulation rose.", "You changed which joints are linked. Use \"Re-generate rig with these points\" instead.": "Vous avez changé les liens entre articulations. Utilisez plutôt « Régénérer le rig avec ces points »."});
  window.FabI18n.register('es', {"Save moved joints": "Guardar las articulaciones movidas", "Saves a new version of the rig with the pink joints where you put them. The mesh does not change.": "Guarda una nueva versión del rig con las articulaciones rosas donde las pusiste. La malla no cambia.", "Move a pink joint first.": "Primero mueve una articulación rosa.", "You changed which joints are linked. Use \"Re-generate rig with these points\" instead.": "Cambiaste qué articulaciones están unidas. Usa «Regenerar el rig con estos puntos»."});
  window.FabI18n.register('zh', {"Save moved joints": "保存移动后的关节", "Saves a new version of the rig with the pink joints where you put them. The mesh does not change.": "以你放置的粉色关节位置保存绑定的新版本。网格不会改变。", "Move a pink joint first.": "请先移动一个粉色关节。", "You changed which joints are linked. Use \"Re-generate rig with these points\" instead.": "你更改了关节之间的连接。请改用“用这些点重新生成绑定”。"});
  window.FabI18n.register('hi', {"Save moved joints": "हिलाए गए जोड़ सहेजें", "Saves a new version of the rig with the pink joints where you put them. The mesh does not change.": "गुलाबी जोड़ों को वहीं रखकर रिग का नया संस्करण सहेजता है जहाँ आपने उन्हें रखा। मेश नहीं बदलता।", "Move a pink joint first.": "पहले कोई गुलाबी जोड़ हिलाएँ।", "You changed which joints are linked. Use \"Re-generate rig with these points\" instead.": "आपने जोड़ों के आपसी संबंध बदल दिए हैं। इसके बजाय \"इन बिंदुओं से रिग फिर से बनाएँ\" का उपयोग करें।"});
  window.FabI18n.register('ar', {"Save moved joints": "حفظ المفاصل المنقولة", "Saves a new version of the rig with the pink joints where you put them. The mesh does not change.": "يحفظ إصدارًا جديدًا من الهيكل مع المفاصل الوردية حيث وضعتها. المجسم لا يتغير.", "Move a pink joint first.": "حرّك مفصلًا ورديًا أولًا.", "You changed which joints are linked. Use \"Re-generate rig with these points\" instead.": "لقد غيّرت الروابط بين المفاصل. استخدم بدلًا من ذلك «إعادة إنشاء الهيكل بهذه النقاط»."});
  // Noms lisibles des versions (2026-09-28). Seul « 3D model » est nouveau :
  // « Rig », « Image », « Animation » ont deja leurs traductions (ne pas ecraser).
  window.FabI18n.register('fr', {"3D model": "Modèle 3D"});
  window.FabI18n.register('es', {"3D model": "Modelo 3D"});
  window.FabI18n.register('zh', {"3D model": "3D 模型"});
  window.FabI18n.register('hi', {"3D model": "3D मॉडल"});
  window.FabI18n.register('ar', {"3D model": "نموذج ثلاثي الأبعاد"});
  // Reshape a region (auto inpaint 3D, 2026-09-28).
  window.FabI18n.register('fr', {"Reshape a region": "Remodeler une zone", "Rebuild ONE part of the model in 3D from a prompt (for example, replace the head). Runs on your graphics card.": "Reconstruit UNE partie du modèle en 3D d'après un prompt (par exemple, remplacer la tête). Tourne sur votre carte graphique.", "Name the part (the AI finds it, or paint it), then describe what should replace it. The AI rebuilds that part in 3D and blends it into the model.": "Nommez la partie (l'IA la trouve, ou peignez-la), puis décrivez ce qui doit la remplacer. L'IA reconstruit cette partie en 3D et la fond dans le modèle.", "What should replace it?": "Par quoi la remplacer ?", "e.g. a crystal skull with two horns": "ex. un crâne de cristal avec deux cornes", "Region rebuilt: new 3D version added.": "Zone reconstruite : nouvelle version 3D ajoutée."});
  window.FabI18n.register('es', {"Reshape a region": "Remodelar una zona", "Rebuild ONE part of the model in 3D from a prompt (for example, replace the head). Runs on your graphics card.": "Reconstruye UNA parte del modelo en 3D a partir de un prompt (por ejemplo, reemplazar la cabeza). Funciona con tu tarjeta gráfica.", "Name the part (the AI finds it, or paint it), then describe what should replace it. The AI rebuilds that part in 3D and blends it into the model.": "Nombra la parte (la IA la encuentra, o píntala) y describe qué debe reemplazarla. La IA reconstruye esa parte en 3D y la funde con el modelo.", "What should replace it?": "¿Qué debe reemplazarla?", "e.g. a crystal skull with two horns": "p. ej. un cráneo de cristal con dos cuernos", "Region rebuilt: new 3D version added.": "Zona reconstruida: nueva versión 3D añadida."});
  window.FabI18n.register('zh', {"Reshape a region": "重塑区域", "Rebuild ONE part of the model in 3D from a prompt (for example, replace the head). Runs on your graphics card.": "根据提示词以 3D 重建模型的某一部分（例如替换头部）。在你的显卡上运行。", "Name the part (the AI finds it, or paint it), then describe what should replace it. The AI rebuilds that part in 3D and blends it into the model.": "说出部位名称（AI 会找到它，或手动涂抹），再描述要替换成什么。AI 会以 3D 重建该部位并融入模型。", "What should replace it?": "用什么替换？", "e.g. a crystal skull with two horns": "例如：带两只角的水晶头骨", "Region rebuilt: new 3D version added.": "区域已重建：已添加新的 3D 版本。"});
  window.FabI18n.register('hi', {"Reshape a region": "किसी क्षेत्र का आकार बदलें", "Rebuild ONE part of the model in 3D from a prompt (for example, replace the head). Runs on your graphics card.": "प्रॉम्प्ट से मॉडल का एक हिस्सा 3D में फिर से बनाएँ (जैसे सिर बदलना)। आपके ग्राफ़िक्स कार्ड पर चलता है।", "Name the part (the AI finds it, or paint it), then describe what should replace it. The AI rebuilds that part in 3D and blends it into the model.": "हिस्से का नाम लिखें (AI उसे ढूँढ लेगा, या उसे पेंट करें), फिर बताएँ कि उसकी जगह क्या आए। AI उस हिस्से को 3D में फिर से बनाकर मॉडल में मिला देता है।", "What should replace it?": "उसकी जगह क्या आए?", "e.g. a crystal skull with two horns": "जैसे दो सींगों वाली क्रिस्टल खोपड़ी", "Region rebuilt: new 3D version added.": "क्षेत्र फिर से बना: नया 3D संस्करण जोड़ा गया।"});
  window.FabI18n.register('ar', {"Reshape a region": "إعادة تشكيل منطقة", "Rebuild ONE part of the model in 3D from a prompt (for example, replace the head). Runs on your graphics card.": "يعيد بناء جزء واحد من النموذج ثلاثي الأبعاد انطلاقًا من وصف (مثل استبدال الرأس). يعمل على بطاقة الرسومات لديك.", "Name the part (the AI finds it, or paint it), then describe what should replace it. The AI rebuilds that part in 3D and blends it into the model.": "اكتب اسم الجزء (يجده الذكاء الاصطناعي، أو لوّنه)، ثم صف ما يجب أن يحل محله. يعيد الذكاء الاصطناعي بناء هذا الجزء ثلاثيًا ويدمجه في النموذج.", "What should replace it?": "بماذا يُستبدل؟", "e.g. a crystal skull with two horns": "مثل جمجمة كريستالية بقرنين", "Region rebuilt: new 3D version added.": "أُعيد بناء المنطقة: أُضيف إصدار ثلاثي الأبعاد جديد."});
  // Reshape (draw), variante manuelle (2026-09-28).
  window.FabI18n.register('fr', {"Reshape (draw)": "Remodeler (pinceau)", "Reshape a region (draw)": "Remodeler une zone (pinceau)", "Paint the part to rebuild straight on the 3D mesh (orbit, zoom, magnifier, undo/redo), then describe what should replace it.": "Peignez la partie à reconstruire directement sur le modèle 3D (rotation, zoom, loupe, annuler/rétablir), puis décrivez ce qui doit la remplacer.", "Rebuild this part": "Reconstruire cette partie", "Part to rebuild": "Partie à reconstruire", "Describe what should replace the part.": "Décrivez ce qui doit remplacer la partie.", "Paint the part to rebuild first (in white).": "Peignez d'abord la partie à reconstruire (en blanc).", "Paint the part to rebuild straight on the 3D model, then describe what should replace it. Runs on your graphics card.": "Peignez la partie à reconstruire directement sur le modèle 3D, puis décrivez ce qui doit la remplacer. Tourne sur votre carte graphique."});
  window.FabI18n.register('es', {"Reshape (draw)": "Remodelar (pincel)", "Reshape a region (draw)": "Remodelar una zona (pincel)", "Paint the part to rebuild straight on the 3D mesh (orbit, zoom, magnifier, undo/redo), then describe what should replace it.": "Pinta la parte a reconstruir directamente sobre el modelo 3D (órbita, zoom, lupa, deshacer/rehacer) y describe qué debe reemplazarla.", "Rebuild this part": "Reconstruir esta parte", "Part to rebuild": "Parte a reconstruir", "Describe what should replace the part.": "Describe qué debe reemplazar la parte.", "Paint the part to rebuild first (in white).": "Primero pinta la parte a reconstruir (en blanco).", "Paint the part to rebuild straight on the 3D model, then describe what should replace it. Runs on your graphics card.": "Pinta la parte a reconstruir sobre el modelo 3D y describe qué debe reemplazarla. Funciona con tu tarjeta gráfica."});
  window.FabI18n.register('zh', {"Reshape (draw)": "重塑（画笔）", "Reshape a region (draw)": "重塑区域（画笔）", "Paint the part to rebuild straight on the 3D mesh (orbit, zoom, magnifier, undo/redo), then describe what should replace it.": "直接在 3D 模型上涂抹要重建的部位（旋转、缩放、放大镜、撤销/重做），然后描述要替换成什么。", "Rebuild this part": "重建此部位", "Part to rebuild": "要重建的部位", "Describe what should replace the part.": "请描述要替换成什么。", "Paint the part to rebuild first (in white).": "请先用白色涂抹要重建的部位。", "Paint the part to rebuild straight on the 3D model, then describe what should replace it. Runs on your graphics card.": "直接在 3D 模型上涂抹要重建的部位，然后描述要替换成什么。在你的显卡上运行。"});
  window.FabI18n.register('hi', {"Reshape (draw)": "आकार बदलें (ब्रश)", "Reshape a region (draw)": "क्षेत्र का आकार बदलें (ब्रश)", "Paint the part to rebuild straight on the 3D mesh (orbit, zoom, magnifier, undo/redo), then describe what should replace it.": "फिर से बनाने वाले हिस्से को सीधे 3D मॉडल पर पेंट करें (घुमाएँ, ज़ूम, आवर्धक, पूर्ववत/फिर करें), फिर बताएँ कि उसकी जगह क्या आए।", "Rebuild this part": "यह हिस्सा फिर से बनाएँ", "Part to rebuild": "फिर से बनाने वाला हिस्सा", "Describe what should replace the part.": "बताएँ कि हिस्से की जगह क्या आए।", "Paint the part to rebuild first (in white).": "पहले फिर से बनाने वाले हिस्से को सफ़ेद रंग से पेंट करें।", "Paint the part to rebuild straight on the 3D model, then describe what should replace it. Runs on your graphics card.": "हिस्से को सीधे 3D मॉडल पर पेंट करें, फिर बताएँ कि उसकी जगह क्या आए। आपके ग्राफ़िक्स कार्ड पर चलता है।"});
  window.FabI18n.register('ar', {"Reshape (draw)": "إعادة التشكيل (فرشاة)", "Reshape a region (draw)": "إعادة تشكيل منطقة (فرشاة)", "Paint the part to rebuild straight on the 3D mesh (orbit, zoom, magnifier, undo/redo), then describe what should replace it.": "لوّن الجزء المراد إعادة بنائه مباشرة على النموذج ثلاثي الأبعاد (تدوير، تكبير، عدسة، تراجع/إعادة)، ثم صف ما يجب أن يحل محله.", "Rebuild this part": "إعادة بناء هذا الجزء", "Part to rebuild": "الجزء المراد إعادة بنائه", "Describe what should replace the part.": "صف ما يجب أن يحل محل الجزء.", "Paint the part to rebuild first (in white).": "لوّن أولًا الجزء المراد إعادة بنائه (بالأبيض).", "Paint the part to rebuild straight on the 3D model, then describe what should replace it. Runs on your graphics card.": "لوّن الجزء مباشرة على النموذج ثلاثي الأبعاد ثم صف ما يجب أن يحل محله. يعمل على بطاقة الرسومات لديك."});
})();
